import "./globals.css";
import Script from "next/script";
import Nav from "./components/Nav";

export const metadata = {
  title: "Megaderu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/img/common/icon/favicon.ico" sizes="any" />
      <body>
        <Nav></Nav>
        {children}
        <Script src="/js/lib/jquery.min.js" strategy="beforeInteractive"/>
        <Script src="/js/common.js" strategy="beforeInteractive"/>
      </body>
    </html>
  );
}
